name: "arrs"
services:
  sonarr:
    image: "11notes/sonarr:4.0.14"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "sonarr.var:/sonarr/var"
    tmpfs:
      - "/tmp:uid=1000,gid=1000" # required for read-only image
    ports:
      - "8989:8989/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  sonarr.var:

networks:
  frontend: