name: "arrs"
services:
  sonarr:
    image: "11notes/sonarr:4.0.15"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "sonarr.etc:/sonarr/etc"
    tmpfs:
      # required for read-only image
      - "/tmp:uid=1000,gid=1000"
    ports:
      - "3000:8989/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  sonarr.etc:

networks:
  frontend: