apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sonarr.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: chown-db-wait
          image: "11notes/k8s-init"
          command:
            - sh
            - -c
            - |
              eleven k8s chown /sonarr {{ .Values.containerSecurityContext.runAsUser | default 1000 }} {{ .Values.containerSecurityContext.runAsGroup | default 1000 }}
              eleven k8s wait postgres {{ .Values.postgres.serviceName }}
          volumeMounts:
            - name: etc
              mountPath: /sonarr/etc
          securityContext:
            runAsUser: 0
      containers:
        - name: sonarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: SONARR__POSTGRES__HOST
              value: {{ .Values.postgres.serviceName | quote }}
            - name: SONARR__POSTGRES__USER
              value: "postgres"
            - name: SONARR__POSTGRES__MAINDB
              value: "postgres"
            - name: SONARR__POSTGRES__MAINDB
              value: "postgres"
            - name: SONARR__POSTGRES__LOGDB
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.secretName" . }}
                  key: {{ include "postgres.secretKey" . }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: sonarr
              containerPort: 8989
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.etc.enabled }}
            - name: etc
              mountPath: /sonarr/etc
            {{- end }}
            - name: tmp
              mountPath: /tmp
      volumes:
        {{- if .Values.persistence.etc.enabled }}
        - name: etc
          persistentVolumeClaim:
            claimName: {{ include "sonarr.claimName" (list . "etc") }}
        {{- end }}
        - name: tmp
          emptyDir:
            medium: Memory
            {{- with .Values.tmpfs.tmp.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
